FROM ghcr.io/imputnet/cobalt:7

# Configure cobalt to run as a standalone API on Hugging Face
ENV COBALT_PORT=7860
ENV COBALT_URL=https://shahandev-downloader.hf.space/
ENV COBALT_BASE_URL=https://shahandev-downloader.hf.space/
ENV COBALT_USE_X_FORWARDED_FOR=true
